version: '3'

networks:
  splunkNet:
    driver: bridge

volumes:
  app-log:

services:
  # Splunk forwarder to send all syslogs to Splunk
  splunk-forwarder:
    container_name: splunk_fwd
    image: 'splunk/universalforwarder:6.5.0'
    environment:
      SPLUNK_FORWARD_SERVER: 'splunk.local:9997'
      SPLUNK_FORWARD_SERVER_ARGS: '-method clone'
      SPLUNK_START_ARGS: '--accept-license --answer-yes'
      SPLUNK_ADD_1: 'udp 1514 -index docker_udp -sourcetype STACK_NAME'
      SPLUNK_ADD_2: 'monitor /var/log/app2/ -index docker_file -sourcetype _json'
      SPLUNK_USER: 'root'
    ports:
      - '514:1514/udp'
    restart: 'always'
    volumes:
      - app-log:/var/log/app2
    networks:
      splunkNet:
        aliases:
          - splunkFwd.local

  # syslog driver Log producer
  app:
    image: 'alpine'
    command: 'sh -c "while true; do echo \"hi `date`\"; sleep 10; done;"'
    logging:
      driver: 'syslog'
      options:
        tag: 'POC_ALPINE'
        syslog-address: 'udp://127.0.0.1'

  # specific fileLog producer
  app2:
    image: 'alpine'
    command: 'sh -c "while true; do echo {\\\"msg\\\":\\\"hOo\\\", \\\"date\\\":\\\"`date`\\\"} > /var/mylogs/myFile`date +%S`.log; sleep 10; done;"'
    volumes:
      - app-log:/var/mylogs
